import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { APP_WEBSITE_URL } from '../config';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Niklas Rydkvist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href={APP_WEBSITE_URL}>Niklas Rydkvist</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <p>Niklas Rydkvist © {new Date().getFullYear().toString()}</p>
      </footer>
    </div>
  );
};

export default Home;
